version: 1.9.95.{branch}.{build}

pull_requests:
  do_not_increment_build_number: true

configuration:
  - Debug
  - Release
  
build:
  project: win32/pcsxr.sln
  verbosity: minimal
  
after_build:
  - cd win32\build\%CONFIGURATION%
  - 7z a pcsxr-pgxp.zip pcsxr-pgxp.exe
  - 7z a pcsxr-pgxp.zip plugins\*.dll

artifacts:
  - path: win32\build\%CONFIGURATION%\pcsxr-pgxp.zip